config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => ''
  root 'index#index'

  resources :restaurants

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/entity.rb
# == Schema Information
#
# Table name: entities
#
#  id             :integer          not null, primary key
#  entity_type_id :integer
#  name           :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  latitude       :float
#  longitude      :float
#  description    :string
#  url            :string
#

class Entity < ActiveRecord::Base
  belongs_to :entity_type
  has_one :review
end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id            :integer          not null, primary key
#  restaurant_id :integer
#  country       :string
#  city          :string
#  address       :string
#  latitude      :float
#  longitude     :float
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Location < ActiveRecord::Base
  belongs_to :restaurant

  geocoded_by :full_street_address
  after_validation :geocode

  def full_street_address
    [ self.address, self.city, self.country ].join(', ')
  end
end

app/models/restaurant.rb
# == Schema Information
#
# Table name: restaurants
#
#  id          :integer          not null, primary key
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  latitude    :float
#  longitude   :float
#  description :string
#  url         :string
#

class Restaurant < ActiveRecord::Base
  has_one :location
  has_one :review

  accepts_nested_attributes_for :location
  accepts_nested_attributes_for :review
end

app/models/review.rb
# == Schema Information
#
# Table name: reviews
#
#  id          :integer          not null, primary key
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  entity_id   :integer          not null
#

class Review < ActiveRecord::Base
  belongs_to :entity
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  role                   :string           default("user"), not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def user?
    role eq 'user'
  end

  def admin?
    role eq 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
    @restaurant.build_location
  end

  def edit
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to restaurants_path, notice: "Created" }
      else
        format.html { redirect_to restaurants_path, alert: 'Creation failed' }
      end
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to restaurants_path, notice: "Updated" }
      else
        format.html { redirect_to restaurants_path, alert: 'Creation failed' }
      end
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :description, location_attributes: [:country, :city, :address])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @restaurants = Restaurant.all
    @gmaps_hash  = Gmaps4rails.build_markers(@restaurants) do |restaurant, marker|
      marker.lat restaurant.location.latitude
      marker.lng restaurant.location.longitude
      marker.infowindow restaurant.name
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basics.
  def full_title(page_title)
    base_title = "UniqRest"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    UniqRest
  </small>
  <nav>
    <ul>
      <!-- <li><%= link_to "About",   '#'   %></li>
      <li><%= link_to "Contact", '#' %></li> -->
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "UniqRest", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if signed_in? %>
            <li><%= link_to "Users", '#' %></li>
            <li><%= link_to "Restaurants", restaurants_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", '#' %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
    <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    <div>
  </body>
</html>

app/views/restaurants/_restaurant.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.simple_fields_for :location do |location_attributes| %>
    <%= location_attributes.input :country %>
    <%= location_attributes.input :city %>
    <%= location_attributes.input :address %>
  <% end %>
  <%= f.input :url %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render 'restaurant' %>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="row page-heading">
    <div class="col-md-12">
      <%= link_to 'New restaurant', new_restaurant_path, class: "btn btn-default pull-right"%>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table">
        <thead>
          <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Address</th>
            <th>Action</th>
          </tr>
        </thead>
        <% @restaurants.each do |restaurant| %>
            <tr>
              <td><%= restaurant.name %></td>
              <td><%= restaurant.description %></td>
              <td><%= restaurant.location.full_street_address %></td>
              <td><%= link_to 'Show', restaurant_path(restaurant) %> | <%= link_to 'Edit', edit_restaurant_path(restaurant) %> | <%= link_to 'Delete', restaurant_path(restaurant), method: 'delete' %></td>
            </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<%= render 'restaurant' %>

app/views/restaurants/show.html.erb
<div class="center-block" style='width: 800px;'>
  <div id="one_marker" style='width: 800px; height: 400px;' data-latitude="<%= @restaurant.location.latitude %>" data-longitude="<%= @restaurant.location.longitude %>" data-title="<%= @restaurant.name %>"></div>
</div>

app/views/static_pages/home.html.erb
<div class="center-block" style='width: 800px;'>
  <div id="geolocation" style='width: 800px; height: 400px;'></div>
</div>

<script>
var handler = Gmaps.build('Google');
handler.buildMap({ internal: {id: 'geolocation'}}, function(){
  var markers = handler.addMarkers(<%=raw @gmaps_hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>